sudo: false
language: node_js
node_js:
  - '4.1'
  - '0.12'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - 'npm install -g bower gulp typescript'

script:
  - 'npm install && bower install && gulp build'
